#!/bin/bash
# Provided by azure extension which comes from template parameters
MIN_HEAP_SIZE=$1
MAX_HEAP_SIZE=$2
CLUSTER_NAME=$3
CLUSTER_PASSWORD=$4
SUBSCRIPTION_ID=$5
AAD_CLIENT_ID=$6
AAD_CLIENT_SECRET=$7
AAD_TENANT_ID=$8
GROUP_NAME=$9
CLUSTER_TAG=${10}
HAZELCAST_VERSION=${11}

chmod +x modify_configuration
# Update hazelcast discovery strategy
./modify_configuration --cluster-name=$CLUSTER_NAME --cluster-password=$CLUSTER_PASSWORD --subscription-id=$SUBSCRIPTION_ID --aad-client-id=$AAD_CLIENT_ID --aad-client-secret=$AAD_CLIENT_SECRET --tenant-id=$AAD_TENANT_ID --group-name=$GROUP_NAME --cluster-tag=$CLUSTER_TAG --filename=hazelcast.xml
# Update hazelcast version, default version 3.7.2
sudo sed -i "s/3.7.2/${HAZELCAST_VERSION}/g" pom.xml
# Update min and max heap
sudo sed -i "s/Xms1G/Xms${MIN_HEAP_SIZE}/g" hazelcast-server.service
sudo sed -i "s/Xmx2G/Xmx${MAX_HEAP_SIZE}/g" hazelcast-server.service

chmod +x install_hazelcast
./install_hazelcast

sudo cp ./hazelcast-server.service /etc/systemd/system
sudo systemctl start hazelcast-server.service
sudo systemctl enable hazelcast-server.service
