#! /bin/bash
sudo apt update
sudo apt install openjdk-8-jre-headless
sudo apt install maven

# Copy configuration files and install
sudo mkdir /var/hazelcast
sudo cp mancenter_hazelcast /var/hazelcast
chmod +x /var/hazelcast/mancenter_hazelcast
sudo cp pom.xml /var/hazelcast
sudo mvn install
sudo cp ./hazelcast.xml /var/hazelcast/
