#! /bin/bash

sudo apt-get update -y
sudo apt-get install openjdk-8-jre -y
sudo apt-get install maven -y

# Copy configuration files and install
sudo mkdir /var/hazelcast
sudo cp pom.xml /var/hazelcast
sudo mvn install
sudo cp ./hazelcast.xml /var/hazelcast/
